vich_uploader:
    db_driver: orm

    mappings:
       property_image:
           uri_prefix: /images/property
           upload_destination: '%kernel.project_dir%/public/images/property'
          
